### PR TITLE
feat: add cluster_primary_security_group_id output [TWO-551, DEVOP-458]

### PR DESCRIPTION
**Pull request by jai**
### Description

* Removes provider version constraints from the inner module, which was causing conflicts with api-cloud-infrastructure
* Removes the provider block from the inner module to comply with [HashiCorp recommendations ](https://www.terraform.io/docs/language/modules/develop/providers.html)
* Makes the `map_users` and `map_roles` variables optional [DEVOP-458]

---
This change is [Reviewable](https://reviewable.io/reviews/honestbank/terraform-aws-eks/19)

### CODE REVIEW

**Review by yotzapon — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/honestbank/terraform-aws-eks/19)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pgcloud and @theerasan)

**Review by theerasan — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/honestbank/terraform-aws-eks/19)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pgcloud)

**Review by pgcloud — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/honestbank/terraform-aws-eks/19)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jai)

**Review by jai — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/honestbank/terraform-aws-eks/19#-:-Mjwh4tQ7V-0oRHJ_IG0:bnfp4nl)* status: 4 of 16 files reviewed, all discussions resolved (waiting on @jai)

**Review by jai — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r5, 7 of 8 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/honestbank/terraform-aws-eks/19)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jai)

**Pull request merged**
