### PR TITLE
feat: add aws-auth ConfigMap output

### PR DESCRIPTION
**Pull request by jai**
### Description

* Adds an output with contents of the `aws-auth` ConfigMap

---
This change is [Reviewable](https://reviewable.io/reviews/honestbank/terraform-aws-eks/16)

### CODE REVIEW

**Review by pgcloud — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/honestbank/terraform-aws-eks/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yoshinaz)

**Review by Yoshinaz — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 2 of 4 files at r4, 1 of 5 files at r5, 4 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/honestbank/terraform-aws-eks/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jai)

**Review by jai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/honestbank/terraform-aws-eks/16)* status: all files reviewed, 1 unresolved discussion (waiting on @jai)

___
*[outputs.tf, line 6 at r7](https://reviewable.io/reviews/honestbank/terraform-aws-eks/16#-MiVfPQoE7T1aqnoC8eC:-MiVfPQoE7T1aqnoC8eD:b-fcsjwu) ([raw file](https://github.com/honestbank/terraform-aws-eks/blob/071f5b9c76de2ccb3f466f99c4d3d19ff262aeee/outputs.tf#L6)):*
> ```HCL
> }
> 
> output "config_map_aws_auth" {
> ```

test comment on output "config_map_aws_auth" `

**Review by poom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/honestbank/terraform-aws-eks/16)* status: all files reviewed, 2 unresolved discussions (waiting on @jai)

___
*[outputs.tf, line 8 at r7](https://reviewable.io/reviews/honestbank/terraform-aws-eks/16#-MiVfk-FDLSgVWzUNNW_:-MiVfk-FDLSgVWzUNNWa:b-gr6y7e) ([raw file](https://github.com/honestbank/terraform-aws-eks/blob/e12749cb3c5e487fcae5d252c97aee7738eb8cae/outputs.tf#L8)):*
> ```HCL
>   description = "Token to access the EKS cluster"
>   value       = module.eks.eks-cluster-token
>   sensitive   = true
> ```

test comment

**Review by poom — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/honestbank/terraform-aws-eks/16)* status: all files reviewed, 3 unresolved discussions (waiting on @jai)

___
*[outputs.tf, line 13 at r7](https://reviewable.io/reviews/honestbank/terraform-aws-eks/16#-MiVgDw05HelhamgedX8:-MiVgDw05HelhamgedX9:b-jf1149) ([raw file](https://github.com/honestbank/terraform-aws-eks/blob/e12749cb3c5e487fcae5d252c97aee7738eb8cae/outputs.tf#L13)):*
> ```HCL
> output "certificate_authority_data" {
>   description = "CA data used to connect to the cluster. Outputted to allow the Kubernetes provider to install the aws_auth config map (allow allocated users to access)"
>   value       = module.eks.certificate_authority_data
> ```

test again

**Pull request closed without merging**
